name = "Planet Viltrum Server"
author = "Snowy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd3c7337a08778c942368c360b2e187635bb6f9fac8a4aa840dabfedb9a17526"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
