name = "Planet Viltrum Server"
author = "Snowy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fc32d33da22cf751f7c8cb5396d81dc176e516aadb35eb32f31d0bdd85e6d18"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
