name = "Planet Viltrum Server"
author = "Snowy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42a501f1550d5a61b5be756fb2d1e05b5cc7cebb12d76d2aec1f1c3d275ec848"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
