name = "Planet Viltrum Server"
author = "Snowy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81fcc962f7949fae11a5f863fdb75c56ca648e02907680f470cb9e9ce0c8b312"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
